version: "3"
services:
  db:
    container_name: database
    image: mongo
    expose:
      - 27017
    volumes:
      - ./database/data/:/data/db
    restart: always

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build: frontend/.
    expose:
      - 3000
    command: npm start
    volumes:
      - ./frontend:/usr/frontend
    restart: always

  backend:
    container_name: backend
    depends_on:
      - db
    build: backend/.
    expose:
      - 80
    volumes:
      - ./backend:/usr/backend
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - db
      - frontend
      - backend
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/logs/:/var/log/nginx/
      - ./nginx/http.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    restart: always